name: Сообщение об ошибке
description: Шаблон для заполнения отчета об ошибке
title: "[Ошибка]: "
labels: ["bug"]
body:
  - type: checkboxes
    id: dupes
    attributes:
      label: Пожалуйста, для начала проверьте наличие дубликатов
      description: Отправляя этот отчет об ошибке вы подтверждаете что предприняли минимальные усилия, для проверки уже существующих проблем, и понимаете что мы можем закрыть вашу проблему, если существует уже похожая.
      options:
        - label: Я проверил систему отслеживания ошибок, и не нашел решения своей (возможно, закрытой) проблемы.
          required: true
  - type: textarea
    id: steps
    attributes:
      label: Действия для воспроизведения ошибки
      description: Четкое, краткое описание ошибки и что вы ожидали.
      value: |
        1. Перейти в ...
        2. Нажать на ...
        3. Увидеть ошибку
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Опишите ожидаемый результат
      description: Четкое и краткое описание того, что вы ожидали.
    validations:
      required: true
  - type: textarea
    id: test
    attributes:
      label: Лабел
      description: Дескриптион
      placeholder: Пласехолдер
      value: "Валуе"
  - type: textarea
    id: actual
    attributes:
      label: Actual results
      description: What actually happened
    validations:
      required: true
  - type: textarea
    id: os-version
    attributes:
      label: Версия Windows
      description: Какую версию Windows вы используете? Note that Insider builds are subject to frequent changes by Microsoft so a bug may not be addressed until the update becomes close to reaching public release.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: Other details
      description: Put other details that you feel could be helpful in diagnosing the problem
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
