name: Предложение функций
description: Шаблон для заполнения предложения функций
title: "[Предложение]: "
labels: ["enhancement"]
body:
  - type: checkboxes
    id: dupes
    attributes:
      label: Пожалуйста, для начала проверьте наличие дубликатов
      description: Отправляя этот отчет об ошибке вы подтверждаете что предприняли минимальные усилия, для проверки уже существующих проблем, и понимаете что мы можем закрыть вашу проблему, если существует уже похожая.
      options:
        - label: Я проверил систему отслеживания ошибок, и не нашел решения своей (возможно, закрытой) проблемы.
          required: true
  - type: textarea
    id: desc
    attributes:
      label: Опишите вашу идею максимально подробно и понятно
    validations:
      required: true
  - type: textarea
    id: help
    attributes:
      label: Опишите возможное решение/реализацию функции (если понимаете как это можно реализовать на Batch/Cmd/PowerShell)
  - type: textarea
    id: other
    attributes:
      label: Остальные мысли о предложенной функции
    validations:
      required: true
