name: Запрос функции
description: Шаблон для заполнения запроса функции
title: "[Запрос функции]: "
labels: ["enhancement"]
assignees: Vijorich
body:
  - type: checkboxes
    id: dupes
    attributes:
      label: Пожалуйста, для начала проверьте наличие дубликатов
      description: Отправляя этот запрос новых функций вы подтверждаете что предприняли минимальные усилия, для проверки уже существующих предложений, и понимаете что мы можем закрыть вашу проблему, если существует уже похожее.
      options:
        - label: Я проверил систему отслеживания ошибок, и не нашел дубликат (возможно, закрытого) предложения функций.
          required: true
  - type: textarea
    id: desc
    attributes:
      label: Опишите вашу идею максимально подробно и понятно
    validations:
      required: true
  - type: textarea
    id: help
    attributes:
      label: Опишите возможное решение/реализацию функции (если понимаете как это можно реализовать на Batch/Cmd/PowerShell)
  - type: textarea
    id: other
    attributes:
      label: Остальные мысли о предложенной функции
