name: Предложение функций
description: Шаблон для заполнения предложения функций
title: "[Предложение]: "
labels: ["enhancement"]
body:
  - type: checkboxes
    id: dupes
    attributes:
      label: Пожалуйста, для начала проверьте наличие дубликатов
      description: Отправляя этот отчет об ошибке вы подтверждаете что предприняли минимальные усилия, для проверки уже существующих проблем, и понимаете что мы можем закрыть вашу проблему, если существует уже похожая или дано недостаточно информаци.
      options:
        - label: Я проверил систему отслеживания ошибок, и не нашел ответа или решения своей (возможно, закрытой) ошибки.
          required: true
