---
name: Предложение функций
about: Шаблон для заполнения предложения функций
title: ''
labels: enhancement
assignees: Vijorich

---

**Опишите вашу идею максимально подробно и понятно.**
Четкое и краткое описание проблемы.

**Опишите желаемое решение или если вы понимаете как это сделать в Batch/Cmd/PowerShell, то возможное решение/реализацию функции**
Четкое и краткое описание того, что вы хотите, чтобы произошло.

**Остальные мысли о предложенной функции**
